AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: >
  Static build of librsvg for Amazon Linux 2 with a Node module

  Check out https://github.com/serverlesspub/rsvg-convert-aws-lambda-binary
  for more information.
Resources:
  RsvgConvertLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: rsvg
      Description: Static build of librsvg with a Node module
      ContentUri: result/
      CompatibleRuntimes:
        - nodejs10.x
      LicenseInfo: https://gitlab.gnome.org/GNOME/librsvg/blob/master/COPYING
      RetentionPolicy: Retain

Outputs:
  LayerVersion:
    Description: Layer ARN Reference
    Value: !Ref RsvgConvertLayer

Metadata:
  AWS::ServerlessRepo::Application:
    Name: rsvg-convert-lambda-layer
    Description: >
      Static build of RsvgConvert for Amazon Linux 2,
      packaged as a Lambda layer. Bundles RsvgConvert 2.26.3.
    Author: Gojko Adzic
    SpdxLicenseId: GPL-2.0
    LicenseUrl: LICENSE.txt
    ReadmeUrl: README-SAR.md 
    Labels: ['layer', 'svg', 'pdf', 'png', 'lambda', 'librsvg', 'rsvg-convert']
    HomePageUrl: https://github.com/serverlesspub/rsvg-convert-aws-lambda-binary
    SemanticVersion: 1.0.0
    SourceCodeUrl: https://github.com/serverlesspub/rsvg-convert-aws-lambda-binary
